steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://miloo-bucket/environments/frigga", "./.env"]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://miloo-bucket/environments/service-account.json", "./service-account.json"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "asia.gcr.io/miloo-phoenix/frigga:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/miloo-phoenix/frigga:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/miloo-phoenix/frigga:latest"]

  - name: "gcr.io/cloud-builders/gke-deploy:stable"
    args:
    - run
    - --filename=deployment.yaml
    - --image=asia.gcr.io/miloo-phoenix/frigga:$SHORT_SHA
    - --location=asia-southeast1-a
    - --cluster=main